source("CodeFlow.R")
png("plot4.png",width = 480,height = 480,units = "px")
par(mfcol = c(2, 2))
plot(reqData[,1],reqData[,2],xlab="", ylab="Global active Power (kilowatts)", type="n")
lines(reqData[,1],reqData[,2])
plot(reqData[,1],reqData[,6],xlab="", ylab="Energy sub metering", type="n")
lines(reqData[,1],reqData[,6])
lines(reqData[,1],reqData[,7],col="red")
lines(reqData[,1],reqData[,8],col="blue")
legend("topright", legend=c("sub_metering_1", "sub_metering_2", "sub_metering_3"),col=c("black","red","blue"),lty=c(1,1), bty = "n")
plot(reqData[,1],reqData[,4],xlab="datetime", ylab="Voltage", type="n")
lines(reqData[,1],reqData[,4])
plot(reqData[,1],reqData[,3],xlab="datetime", ylab="Global_reactive_power", type="n")
lines(reqData[,1],reqData[,3])
dev.off()